#Cats
#Run the following code to import the cats data set from the “MASS” library.  
#library(MASS) 
#data(cats)

#The data set includes 3 variables: Sex, Body weight (kg) and heart weight (g). These variable can be found with the str() function.  


```{r}
library(MASS)
data(cats)
str(cats)

#Create a linear model where heart weight is the dependent variable and body weight is the independent variable.
model<- lm(Hwt~Bwt, data=cats)
plot(cats$Bwt, cats$Hwt, las=1, type="n")

#What is the intercept and the slope of this model? How can you interpret the slope of this model?
abline(lm(Hwt~Bwt, data=cats))

#Now draw a scatter plot with this data and insert this linear model into it. Try to distinguish the sex of the cats in the scatter plot.
with(cats, points(Bwt[Sex=="F"], Hwt[Sex=="F"], pch=16, col="red"))
with(cats, points(Bwt[Sex=="M"], Hwt[Sex=="M"], pch=17, col="blue"))

max(cats$Bwt)

#Predict the heart weight of a cat that is 3.5 kilograms. Can you accurately predict the heart weight of a cat that is 6.5 kilograms?
#prediction for cat model for Hwt of a cat with Bwt = 3.5
summary(model)
new.df <- data.frame(Bwt=c(3.5))
predict(model, new.df)
```

#############################################
```{r}
#   Mtcars

#First, model the mpg variable on hp and then model the mpg variable on wt. Check the summary commend for both of the models.
#data(Mtcars)

data(mtcars)
str(mtcars)
model1 <- lm(mpg ~ hp, data=mtcars)
summary(model1)
model2 <- lm(mpg~wt, data=mtcars)
summary(model2)
```
###############################################
```{r}
#   Wage

#Run the following code to import the Wage data set from the “ISLR” library.  
#library(ISLR)
#data(Wage) 

#Explore the variables of the dataset using str()or with "?Wage." Build a regression model where wage is the dependent variable and age, 
#job class (which has 1 for Industrial and 2 for Information) and education are the independent variable. 
#How can we interpret the slope of age? Keep in mind that this definition will be slightly different then the previous ones as we 
#have multiple variables in the model.

library(ISLR)
data(Wage)
str(Wage)
lm(wage~age+education+jobclass, data=Wage)
```
##############################################
```{r}
#   Hsb

#Run the following code to import the hsb data set from the “faraway” library.
#library(faraway)
#data(hsb)

#Build a linear regression model for the response variable “science”. Use all the other variables in the dataset as independent variables.

library(faraway)
data(hsb)
str(hsb)
g1 <- lm(science~gender+race+ses+schtyp+prog+
          read+write+socst, data=hsb)
summary(g1)        
```
###############################################

